'use strict';
const mons=POKE_DATA.mons;
const $=id=>document.getElementById(id);let current='guess',score=0,round=0,deck=[],answered=false,timeout=null,flips=[],pairs=0,moves=0,locked=false;
let activeRandom=Math.random;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(activeRandom()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a};
function update(){ $('score').textContent=String(score).padStart(3,'0');$('progress').textContent=current==='grid'?`CASILLAS ${gridCells.filter(c=>c.answer).length} / ${gridCells.filter(c=>c.candidates.length).length}`:current==='top10'?`ENCONTRADOS ${topFound.length} / 10`:current==='memory'?`PAREJAS ${pairs} / 6 · INTENTOS ${moves}`:`RONDA ${Math.min(round+1,5)} / 5`; }
function start(game){if(!['guess','quiz','grid','top10','connections','stats700','impostor','pokedle','speed','evolution','battle'].includes(game))throw new Error('Juego no válido');clearTimeout(timeout);clearInterval(clock);$('grid-dialog').close();current=game;topStarted=false;topFinished=false;topFound=[];score=0;round=0;answered=false;flips=[];pairs=0;moves=0;locked=false;$('feedback').replaceChildren();document.querySelectorAll('[data-game]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.game===current)));$('pool-count').textContent=`${eligible().length} Pokémon disponibles`;const labels={grid:['CRUZÁ CRITERIOS','Cuadrícula Pokémon'],top10:['COMPLETÁ LA LISTA','Top 10 Pokémon'],guess:['DESAFÍO DE SILUETAS','¿Quién es ese Pokémon?'],memory:['ENCONTRÁ LAS PAREJAS','Memoria Pokémon'],quiz:['PONÉ A PRUEBA TU POKÉDEX','Quiz Pokémon']};$('game-label').textContent=labels[current][0];$('game-title').textContent=labels[current][1];if(game==='grid'){const puzzle=buildGrid(eligible());gridRows=puzzle.rows;gridCols=puzzle.cols;gridCells=puzzle.cells;renderGrid();update();return;}if(game==='top10'){renderTopSetup();update();return;}const pool=game==='guess'&&typeof dailyDistinctOrder==='function'&&!(typeof infiniteMode!=='undefined'&&infiniteMode)?dailyDistinctOrder(eligible(),'guess'):shuffle(eligible());deck=game==='quiz'?makeQuiz(eligible()):pool.slice(0,game==='memory'?6:5);if(current==='memory'){deck=shuffle([...deck,...deck].map((m,index)=>({...m,index})));renderMemory();}else renderRound();update();}
function result(){ typeof markDailyPlayed==='function'&&markDailyPlayed(current,score/500>.65);$('game').innerHTML=`<div class="result"><span class="eyebrow">DESAFÍO COMPLETADO</span><div class="big">${score}</div><h3>${current==='memory'?'¡Todas las parejas!':score===500?'¡Maestro Pokémon!':score/500>.65?'¡Victoria diaria!':'¡Seguí entrenando!'}</h3><p>${current==='memory'?`Encontraste 6 parejas en ${moves} intentos.`:`Acertaste ${score/100} de 5. Cada partida es un nuevo desafío.`}</p><button class="play-again">Jugar otra vez</button></div>`;$('feedback').replaceChildren();$('progress').textContent='PARTIDA TERMINADA';document.querySelector('.play-again').onclick=()=>start(current);}
function renderRound(){answered=false;$('feedback').replaceChildren();if(round>=5){result();return;}const item=deck[round];let options;
 if(current==='guess'){const wrongCount=gameDifficulty==='easy'?2:gameDifficulty==='expert'?5:3;options=shuffle([item,...shuffle(eligible().filter(m=>m.id!==item.id)).slice(0,wrongCount)]);const hint=gameDifficulty==='easy'?`Pista: ${typeLabel(item)} · Generación ${item.gen}`:gameDifficulty==='expert'?'Sin pistas y con seis opciones.':'Reconocé la silueta y elegí su nombre.';$('game').innerHTML=`<div class="guess-layout"><div class="pokemon-stage"><img class="silhouette${gameDifficulty==='easy'?' silhouette-easy':''}" src="${spriteUrl(item.sprite)}" alt="Silueta de un Pokémon para adivinar"><span class="stage-label">POKÉDEX · ???</span></div><div class="answer-panel"><p>${hint}</p><div class="answers"></div></div></div>`;}else{$('game').innerHTML=`<p class="question"></p>${gameDifficulty==='easy'?'<p class="grid-note">Tres opciones.</p>':gameDifficulty==='expert'?'<p class="grid-note">Seis opciones.</p>':''}<div class="answers quiz-answers"></div>`;document.querySelector('.question').textContent=item.q;options=item.options;}
 const area=document.querySelector('.answers');options.forEach((o,i)=>{const b=document.createElement('button');if(current==='guess')b.textContent=o.name;else{b.innerHTML=typeBadgesFromLabel(o);b.setAttribute('aria-label',o);}b.onclick=()=>choose(i,options);area.append(b);});update();}
function choose(index,options){if(answered||round>=5)return;const item=deck[round];answered=true;const correct=current==='guess'?options.findIndex(m=>m.id===item.id):item.answer;const good=index===correct;if(good)score+=100;const buttons=document.querySelectorAll('.answers button');buttons.forEach((b,i)=>{b.disabled=true;if(i===correct)b.classList.add('correct');else if(i===index)b.classList.add('wrong');});if(current==='guess'){const im=document.querySelector('.pokemon-stage img');im.classList.remove('silhouette');im.alt=item.name;document.querySelector('.stage-label').textContent=`POKÉDEX · #${String(item.id).padStart(3,'0')}`;}$('feedback').textContent=(good?'¡Correcto! +100 puntos. ':'¡A seguir entrenando! ')+(current==='guess'?`Es ${item.name}.`:item.note);const next=document.createElement('button');next.className='next';next.textContent=round===4?'Ver resultado':'Siguiente →';next.onclick=()=>{round++;renderRound();};$('feedback').append(next);update();}
function renderMemory(){ $('game').innerHTML='<p class="memory-info">Da vuelta dos cartas. Encontrá las 6 parejas.</p><div class="memory-grid"></div>';const grid=document.querySelector('.memory-grid');deck.forEach((m,i)=>{const b=document.createElement('button');b.className='memory-card';b.textContent='?';b.setAttribute('aria-label',`Carta ${i+1}, oculta`);b.onclick=()=>flip(i);grid.append(b);}); }
function showCard(i,visible){const b=document.querySelectorAll('.memory-card')[i],m=deck[i];b.classList.toggle('flipped',visible);b.innerHTML=visible?`<img src="${spriteUrl(m.sprite)}" alt="${m.name}">`:'?';b.setAttribute('aria-label',visible?`Carta ${i+1}, ${m.name}`:`Carta ${i+1}, oculta`);}
function flip(i){const cards=document.querySelectorAll('.memory-card');if(current!=='memory'||locked||cards[i].disabled||flips.includes(i))return;showCard(i,true);flips.push(i);if(flips.length<2)return;moves++;const [a,b]=flips;if(deck[a].id===deck[b].id){pairs++;score+=100;cards[a].disabled=cards[b].disabled=true;cards[a].classList.add('matched');cards[b].classList.add('matched');flips=[];$('feedback').textContent='¡Pareja encontrada! +100 puntos.';update();if(pairs===6){locked=true;timeout=setTimeout(result,650);}}else{locked=true;$('feedback').textContent='No son iguales. ¡Probá otra vez!';update();timeout=setTimeout(()=>{showCard(a,false);showCard(b,false);flips=[];locked=false;},850);}}
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));$('restart').onclick=()=>start(current);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'start_pokemon_game',title:'Empezar minijuego Pokémon',description:'Abre un minijuego. Reto 700 retoma la partida pendiente y conserva su Pokémon; Top 10 y Conexiones abren su configuración.',inputSchema:{type:'object',properties:{game:{type:'string',enum:['guess','quiz','grid','top10','connections','stats700','impostor','pokedle','speed','evolution','battle']}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length!==1||!['guess','quiz','grid','top10','connections','stats700','impostor','pokedle','speed','evolution','battle'].includes(input.game))throw new Error('Elegí un juego disponible, incluida battle para Batalla de Gimnasio');start(input.game);return{game:current,score,started:!['top10','connections'].includes(current)};}})).catch(()=>{});}catch{}}
